### PR TITLE
build.sh will run sh cli tests

### LINKED ISSUE #20: Extend CI to run shell unit tests testing CLI commands
**Describe the request**
CI setup currently run Sunit tests executed in Pharo. For CLI testing purposes, we want to run CI also tests that are bash specific and testing CLI Pharo Launcher commands.

**Expected behavior**  
CI runs bash unit tests specific to CLI of Pharo Launcher and reports potential issues as result of build process.  

**Expected development cost**
- implement new sh function in `build.sh` script called e.g.: `runBashPharoLauncherCLITests()` that would implement something like:
```
#!/bin/bash
set -e
for f in test*.sh; do
  bash "$f"
done
```
- modify `run_tests()` function in `build.sh` to run newly created function (in previous step)

**Opened questions**
- how sh unit test produce output? Is there something like `--junit-xml-output` option?
- where are test artefacts (xml with results) produced?
- Can we make sh unit tests running also on Windows platform?

### PR DESCRIPTION
**Pull request by Bajger**
Added invoking of shell integration tests to test Pharo Launcher CLI
fixes #20

### CODE REVIEW

**Comment by Bajger** [comment]
Unfortunatelly running locally on my Ubuntu Linux didn't succeed:
```
/pharo-launcher.sh: line 8: Linux=/home/dbajger/pharolauncher/pharo-vm/pharo: No such file or directory
./pharo-launcher.sh: line 25: : command not found
shunit2:FATAL oneTimeSetUp() returned non-zero return code.
./pharo-launcher.sh: line 8: Linux=/home/dbajger/pharolauncher/pharo-vm/pharo: No such file or directory
./pharo-launcher.sh: line 25: : command not found
shunit2:WARN oneTimeTearDown() returned non-zero return code.
ASSERT:unknown failure encountered running a test

Ran 0 tests.

FAILED (failures=1)
```
@demarey : Do you know, how to reliably detect vm and image name (path)? Obviously used path in `pharo-launcher.sh` script is valid after packaging, but not before during prepare phase.

This was my testing procedure: 
```
gh repo clone PharoLauncherCmdLine/CommandLineLauncher
cd CommandLineLauncher
PHARO=80 ARCHITECTURE=64 ./build.sh prepare
PHARO=80 ARCHITECTURE=64 ./build.sh test
```

**Comment by Bajger** [comment]
should be working now.

**Comment by demarey** [comment]
Thanks for this work @Bajger .
If you take a look at https://github.com/PharoLauncherCmdLine/CommandLineLauncher/blob/dev/script/pharo-launcher.sh, you will see that the script is very different than the one in this branch. It is very closed to zero-conf script (using get.pharo.org/xx). It is the script that will be delivered and I think it is good to keep it as it is.
Also, there is a problem for testing as the folder layout is not the same as the one when pharo launcher is installed.
As we are doing functional testing (black box) of pharo launcher command line, I would not update the script to manage the test case (not the instructions that will be used by final users) but I would rather create an environment that is almost the same as in production, and use `pharo-launcher.sh`as in production. It means, on linux:
- create a directory  named `shared` with a copy of the launcher image (to remove after tests)
- copy `pharo-launcher.sh` script aside the `pharo-vm` directory 

WDYT?

**Comment by Bajger** [comment]
@demarey: Hi Christophe, thanks for your insight! One of my concern was that I didn't like a fact that pharo-launcher.sh is dependent on directory where user currently operates. There has to be exact directory set, otherwise it won't work. So when users would use Launcher CLI, then they need to set directory first in order to use it. For me, it is usability concern. (why to limit users to be in given directory?)

Anyway, I'll try to use your approach (with copying image and script) and let you know then. 
Question: Is pharo-launcher.sh that is put aside to vm executable a deployment artefact? Or it should be removed after test as well? 
Maybe I'm a bit lost with each phase (before creating deployment artefacts/package and and after that)

**Comment by demarey** [comment]
> One of my concern was that I didn't like a fact that pharo-launcher.sh is dependent on directory where user currently operates.

You're right! That's why https://github.com/PharoLauncherCmdLine/CommandLineLauncher/blob/dev/script/pharo-launcher.sh is only bound to the location where Pharo Launcher is installed. Then, you add `pharo-launcher.sh` directory to your PATH and you can use it from any location.
`pharo-launcher.sh` is not meant to be moved at any place in the system.

`pharo-launcher.sh` is copied in the packaging step of the build. You can see it at https://github.com/PharoLauncherCmdLine/CommandLineLauncher/blob/dev/build.sh#L71
What I suggested to do not pollute the workspace when testing is to copy everything you need in a folder and drop it after testing (probably only the vm and the script).

**Comment by Bajger** [comment]
@demarey: Fixed how pharo launcher script should be called based on your recommendations. There is just one detail: 
`pharo-launcher.sh` is expected to be in root dir (where repo is cloned).
Tests are now failing, but it is problem of kill command (created separate issue #22 ), in general mechanism of calling from build.sh should be fixed now. 
Reprosteps are:
```
gh repo clone PharoLauncherCmdLine/CommandLineLauncher
cd CommandLineLauncher
git checkout 20-Extend-CI-to-run-shell-unit-tests-testing-CLI-commands
PHARO=80 ARCHITECTURE=64 ./build.sh prepare
PHARO=80 ARCHITECTURE=64 ./build.sh test
```
I think PR can be closed now

**Review by demarey — APPROVED** [review]

**Pull request merged**
