### PR TITLE
28-Adjust-list-command-with-pretty-print-format

### LINKED ISSUE #28: Adjust list command with pretty print format
_Currently, list commands lists only sequence nr. and name of image and VM (or template). This is insufficient, when compared to UI version._

**Describe the request**
Lists commands should output pretty print format with useful information (as described [here](https://github.com/PharoLauncherCmdLine/CommandLineLauncher/commit/a6c725cc3a3dadd02e8572a8ab05b14a992d3ee2#diff-c716a6a7c64224417d663d79fa12fc5caddbfe925600c575e274ad66778a9fc6)

**Expected behavior**
Image and VM list commands should output following:
- Image: nr., Image name, Architecture, Pharo Version, Last Modified, Last Modified ago
- VM:  nr., VM name, Updated, Remote URL

2) provide additional flags for print format
- short version of output using `brief` flag that will print just name
- `delimiter` flag for custom delimiter when printing image or VM attributes
- `rowMode` - prints one attribute per line only

**Expected development cost**
adjust `list:` method for listing attributes in table format and in block mode

### PR DESCRIPTION
**Pull request by Bajger**
Changes related to cli list print formatter, fixes in commands and its unit tests

### CODE REVIEW

**Comment by Bajger** [comment]
@demarey: I know it is pretty extensive PR. All unit tests should be passing. Please feel free to review, as you've time.

**Comment by demarey** [comment]
I did not finished the review but I did a PR for formatting / naming issues mainly.
I'm now surprised to see labels and print blocks used by some commands for printing defined on the domain objects.
The way these domain objects will be displayed/printed is the responsibility of the command. I would rather define labels and print blocks on the command object. WDYT?

**Comment by Bajger** [comment]
@demarey Hi Christophe! Based on what I recall I defined print methods for blocks and labels on domain objects for few reasons:
- it seems to be analogous to casual printOn: method, which is defined on any Object subclass
- to me it is responsibility of object, how to print itself. I'm trying to avoid own command logic on cli commnads and rather use core logic around. CLI version should probably just keep presence of arguments and their validity. 
- reason why not responsibility of cli command is that it can be reused later in core commands, which are used in spec version. So spec version can use same method as cli version (maybe cli version differs a bit, but I don't know if it differs, probably not). So these methods on domain objects could be moved to core launcher package later.
Anyway, let me know if you still consider better to have it on CLI command, I can move it and submit additional commit.

**Comment by demarey** [comment]
I do not think core commands will reuse the printing of CLI commands. The way they are defined are very different.
I now do see why you defined printing blocs in the domain objects. I'm ok to keep as it is. Thank you. for the explanation

**Comment by Bajger** [comment]
@demarey : Tests are passing (except PhLImageTest>>testPhLImageSerialization), can be merged.

**Review by demarey — APPROVED** [review]

**Pull request merged**
